# From https://github.com/ioos/ioos_qc/blob/939de10170f50f2aea4df0fe007c8e38ca6ee9f1/ioos_qc/config.py#L352-L365
region: None
window:
    starting: 2020-01-01T00:00:00Z
    ending: 2020-04-01T00:00:00Z
streams:
    variable1:    # stream_id
        qartod:   # Config
            location_test:
                bbox: [-80, 40, -70, 60]
    variable2:    # stream_id
        qartod:   # Config
            gross_range_test:
                suspect_span: [1, 11]
                fail_span: [0, 12]
