# From https://github.com/ioos/ioos_qc/blob/939de10170f50f2aea4df0fe007c8e38ca6ee9f1/tests/test_config.py#L28-L37
variable1:
  not_a_module:
  qartod:
      gross_range_test:
          suspect_span: [1, 11]
          fail_span: [0, 12]
      location_test:
          bbox: [-80, 40, -70, 60]
      not_a_test:
          foo: [1, null]
