# From https://github.com/ioos/ioos_qc/blob/939de10170f50f2aea4df0fe007c8e38ca6ee9f1/tests/test_config.py#L74-L83
streams:
    variable1:
        qartod:
            location_test:
                bbox: [-80, 40, -70, 60]
    variable2:
        qartod:
            gross_range_test:
                suspect_span: [1, 11]
                fail_span: [0, 12]
