use crate::standard::Standard;

// Loads CF HashMap functions that are generated by build.rs.
// Update the standards from source xmls with `uv run --script utils/update_standards.py`
include!(concat!(env!("OUT_DIR"), "/build_standards.rs"));

/// Returns a HashMap of standard names: vector of aliases
pub fn aliases_by_standard_name() -> HashMap<&'static str, Vec<&'static str>> {
    let aliases = generated_cf_aliases();

    let mut standards = HashMap::new();

    for (alias, standard_name) in aliases {
        standards
            .entry(standard_name)
            .or_insert_with(Vec::new)
            .push(alias);
    }

    standards
}

/// Returns a HashMap of standard names to Standard
pub fn cf_standards() -> HashMap<String, Standard> {
    let alias_map = aliases_by_standard_name();

    let mut standards = HashMap::new();

    for (name, unit, description) in CF_TUPLE {
        let empty_vec = Vec::new();
        let aliases = alias_map.get(name).unwrap_or(&empty_vec);
        let aliases = aliases.iter().map(|alias| alias.to_string()).collect();

        standards.insert(
            name.to_string(),
            Standard {
                name: name.to_string(),
                unit: unit.to_string(),
                description: description.to_string(),
                aliases,
                ..Standard::default()
            },
        );
    }

    standards
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_load_cf_aliases() {
        let aliases = aliases_by_standard_name();

        let pressure = aliases["air_pressure_at_mean_sea_level"].clone();
        assert!(
            pressure.contains(&"air_pressure_at_sea_level"),
            "The standard `air_pressure_at_mean_sea_level` should contain the alias `air_pressure_at_sea_level`"
        )
    }

    #[test]
    fn load_cf_standards() {
        let standards = cf_standards();
        let pressure = standards["air_pressure_at_mean_sea_level"].clone();
        assert_eq!(pressure.name, "air_pressure_at_mean_sea_level");

        println!("Name is correct");

        assert!(
            pressure
                .aliases
                .contains(&"air_pressure_at_sea_level".to_string()),
            "The standard `air_pressure_at_mean_sea_level` should contain the alias `air_pressure_at_sea_level`"
        )
    }
}
